version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_smokegames
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: smokegames_bd
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api-service:
    image: 262018804298.dkr.ecr.us-east-1.amazonaws.com/smokegames-back:latest 
    container_name: smokegames_backend
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/smokegames_bd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_smokegames
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_smokegames
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
