services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_smokegames
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Cambia esto si lo prefieres
      MYSQL_DATABASE: smokegames_bd
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api-service:
    build: ./SmokeGameBack
    container_name: smokegames_backend
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/smokegames_bd?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password