name: CI/CD Pipeline Enterprise

on:
  push:
    branches: [ "ramaHTML" ]

jobs:
  # 1. Escaneo de seguridad (Requisito profe)
  security-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snyk Security Scan
        uses: snyk/actions/maven@master
        continue-on-error: true 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          # Ahora buscamos en la raíz, donde pusiste el pom.xml
          args: --file=pom.xml --severity-threshold=high --json-file-output=snyk_report.json

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report
          path: snyk_report.json

  # 2. Build y Tests con JaCoCo (Requisito profe)
  build-and-test:
    name: Build & Test
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and Test
        # Aquí eliminamos el working-directory porque ya no está en SmokeGameBack
        run: mvn clean verify -Dspring.profiles.active=test
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

  # 3. Despliegue automático a AWS (ECR + EC2)
  docker-deploy:
    name: Build, Push & Deploy
    needs: build-and-test
    runs-on: self-hosted
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Login Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_REGION: us-east-1

      - name: Build y Push a ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: smokegames-back
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy con Docker Compose
        run: |
          docker compose pull
          docker compose up -d --force-recreate
